### ISSUE TITLE
Error:(39, 13) Failed to resolve: com.afollestad:material-dialogs:0.6.0

### ISSUE THREAD

**Issue by Technologx** [Supremez/Dashboard#10]
Error:(39, 13) Failed to resolve: com.afollestad:material-dialogs:0.6.0
<a href="openFile:/Users/Technologx/Downloads/Dashboard-master/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

How do I fix this?

**Comment by timbremer** [comment]
Update the dependency to the latest MaterialDialogs version (0.9.0.1) in the build.gradle
`compile 'com.afollestad.material-dialogs:core:0.9.0.1`

**Comment by Technologx** [comment]
Alright now I'm running into this:
Error:(1, 0) Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "578a7517c5bd373b13c57690bbf83c5d5d6143c7"
<a href="fixGradleElements">Fix plugin version and sync project</a><br><a href="openFile:/Users/Technologx/Downloads/Dashboard-master/app/build.gradle">Open File</a>

**Comment by Technologx** [comment]
Alright I got that fixed and the gradle version updated I am now running into this and have no idea what to do.

Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies]
/Users/Technologx/Downloads/Dashboard-master/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/Technologx/Library/Android/sdk/build-tools/21.1.2/aapt'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 35.824 secs
Error:AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027android:TextAppearance.Material.Widget.Button.Inverse\u0027.","sources":[{"file":"/Users/Technologx/Downloads/Dashboard-master/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml","position":{"startLine":3}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027android:Widget.Material.Button.Colored\u0027.","sources":[{"file":"/Users/Technologx/Downloads/Dashboard-master/app/build/intermediates/res/merged/debug/values-v23/values-v23.xml","position":{"startLine":33}}],"original":"","tool":"AAPT"}
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/Technologx/Library/Android/sdk/build-tools/21.1.2/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Information:4 errors

**Comment by timbremer** [comment]
I just updated this 2 year old project for you, fetch the latest changes, import the project to Android Studio and you should be good to go!

**Comment by Technologx** [comment]
Thank you man this will be put to good use
