### ISSUE TITLE
Running into another issue

### ISSUE THREAD

**Issue by Technologx** [Supremez/Dashboard#12]
Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/BaseActivity.java
Error:(24, 30) error: cannot find symbol class R
Error:(37, 43) error: package R does not exist
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java
Error:(27, 30) error: cannot find symbol class R
Error:(55, 48) error: package R does not exist
Error:(56, 51) error: package R does not exist
Error:(78, 17) error: package R does not exist
Error:(84, 36) error: package R does not exist
Error:(94, 20) error: package R does not exist
Error:(97, 20) error: package R does not exist
Error:(99, 52) error: package R does not exist
Error:(142, 9) error: constructor Crop in class Crop cannot be applied to given types;
required: Uri,Uri
found: Uri
reason: actual and formal argument lists differ in length
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java
Error:(39, 30) error: cannot find symbol class R
Error:(52, 27) error: package R does not exist
Error:(53, 54) error: package R does not exist
Error:(60, 77) error: package R does not exist
Error:(64, 47) error: package R does not exist
Error:(65, 33) error: package R does not exist
Error:(82, 17) error: package R does not exist
Error:(87, 36) error: package R does not exist
Error:(136, 26) error: package R does not exist
Error:(139, 74) error: package R does not exist
Error:(140, 61) error: package R does not exist
Error:(141, 72) error: package R does not exist
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java
Error:(90, 20) error: method onCreate(Bundle) is already defined in class AboutActivity
Error:(29, 25) error: package R does not exist
Error:(30, 43) error: package R does not exist
Error:(38, 43) error: package R does not exist
Error:(42, 43) error: package R does not exist
Error:(46, 55) error: package R does not exist
Error:(56, 54) error: package R does not exist
Error:(66, 55) error: package R does not exist
Error:(78, 58) error: package R does not exist
Error:(92, 25) error: package R does not exist
Error:(93, 43) error: package R does not exist
Error:(101, 43) error: package R does not exist
Error:(105, 43) error: package R does not exist
Error:(109, 55) error: package R does not exist
Error:(119, 55) error: package R does not exist
Error:(131, 58) error: package R does not exist
Error:(146, 36) error: package R does not exist
Error:(158, 20) error: package R does not exist
Error:(163, 19) error: package R does not exist
Error:(169, 39) error: package R does not exist
Error:(171, 65) error: package R does not exist
Error:(172, 42) error: package R does not exist
Error:(174, 65) error: package R does not exist
Error:(175, 42) error: package R does not exist
Error:(179, 67) error: package R does not exist
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java
Error:(45, 43) error: package R does not exist
Error:(51, 43) error: package R does not exist
Error:(55, 43) error: package R does not exist
Error:(61, 43) error: package R does not exist
Error:(66, 60) error: package R does not exist
Error:(67, 73) error: package R does not exist
Error:(97, 75) error: package R does not exist
Error:(102, 75) error: package R does not exist
Error:(208, 47) error: package R does not exist
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/CalligraphyApplication.java
Error:(19, 41) error: package R does not exist
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java
Error:(20, 17) error: package R does not exist
Error:(28, 36) error: package R does not exist
Error:(40, 20) error: package R does not exist
Error:(44, 20) error: package R does not exist
Error:(51, 19) error: package R does not exist
Error:(57, 39) error: package R does not exist
Error:(59, 65) error: package R does not exist
Error:(60, 42) error: package R does not exist
Error:(62, 65) error: package R does not exist
Error:(63, 42) error: package R does not exist
Error:(67, 67) error: package R does not exist
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 38.713 secs
Error:/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/BaseActivity.java:24: error: cannot find symbol
import com.supremez.dashboard.R;
                             ^
  symbol:   class R
  location: package com.supremez.dashboard
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:27: error: cannot find symbol
import com.supremez.dashboard.R;
                             ^
  symbol:   class R
  location: package com.supremez.dashboard
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:39: error: cannot find symbol
import com.supremez.dashboard.R;
                             ^
  symbol:   class R
  location: package com.supremez.dashboard
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:90: error: method onCreate(Bundle) is already defined in class AboutActivity
    protected void onCreate(Bundle savedInstanceState) {
                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/BaseActivity.java:37: error: package R does not exist
        toolbar = (Toolbar) findViewById(R.id.toolbar);
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:55: error: package R does not exist
        mImageView = (ImageView) findViewById(R.id.image);
                                               ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:56: error: package R does not exist
        progressBar = (ProgressBar) findViewById(R.id.loading);
                                                  ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:78: error: package R does not exist
        return R.layout.activity_detail;
                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:84: error: package R does not exist
        getMenuInflater().inflate(R.menu.wallpaper, menu);
                                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:94: error: package R does not exist
        if (id == R.id.action_settings) {
                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:97: error: package R does not exist
        if (id == R.id.set_wall) {
                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:99: error: package R does not exist
            mImageView = (ImageView) findViewById(R.id.image);
                                                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/DetailActivity.java:142: error: constructor Crop in class Crop cannot be applied to given types;
        new Crop(source).output(outputUri).withMaxSize(width, height).start(this);
        ^
  required: Uri,Uri
  found: Uri
  reason: actual and formal argument lists differ in length
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:52: error: package R does not exist
        setActionBarIcon(R.drawable.ic_ab_drawer);
                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:53: error: package R does not exist
        GridView gridView = (GridView) findViewById(R.id.gridView);
                                                     ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:60: error: package R does not exist
                DetailActivity.launch(HomeActivity.this, view.findViewById(R.id.image), url);
                                                                            ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:64: error: package R does not exist
        drawer = (DrawerLayout) findViewById(R.id.drawer);
                                              ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:65: error: package R does not exist
        drawer.setDrawerShadow(R.drawable.drawer_shadow, Gravity.START);
                                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:82: error: package R does not exist
        return R.layout.activity_home;
                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:87: error: package R does not exist
        getMenuInflater().inflate(R.menu.grid_menu, menu);
                                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:136: error: package R does not exist
                        R.layout.grid_item, viewGroup, false);
                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:139: error: package R does not exist
                viewHolder.image = (ImageView) convertView.findViewById(R.id.image);
                                                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:140: error: package R does not exist
                viewHolder.view = convertView.findViewById(R.id.view);
                                                            ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/antonioleiva/materialeverywhere/HomeActivity.java:141: error: package R does not exist
                viewHolder.text = (TextView) convertView.findViewById(R.id.textpalette);
                                                                       ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:29: error: package R does not exist
        setContentView(R.layout.activity_about);
                        ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:30: error: package R does not exist
        toolbar = (Toolbar) findViewById(R.id.toolbar);
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:38: error: package R does not exist
                    .playOn(findViewById(R.id.card_view1));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:42: error: package R does not exist
                    .playOn(findViewById(R.id.card_view2));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:46: error: package R does not exist
        ImageView plustim = (ImageView) findViewById(R.id.gplus_tim);
                                                      ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:56: error: package R does not exist
        ImageView gittim = (ImageView) findViewById(R.id.github_tim);
                                                     ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:66: error: package R does not exist
        ImageView mailtim = (ImageView) findViewById(R.id.mail_tim);
                                                      ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:78: error: package R does not exist
        ImageView twittertim = (ImageView) findViewById(R.id.twitter_tim);
                                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:92: error: package R does not exist
        setContentView(R.layout.activity_about);
                        ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:93: error: package R does not exist
        toolbar = (Toolbar) findViewById(R.id.toolbar);
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:101: error: package R does not exist
                    .playOn(findViewById(R.id.card_view1));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:105: error: package R does not exist
                    .playOn(findViewById(R.id.card_view2));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:109: error: package R does not exist
        ImageView plustim = (ImageView) findViewById(R.id.gplus_technologx);
                                                      ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:119: error: package R does not exist
        ImageView mailtim = (ImageView) findViewById(R.id.mail_technologx);
                                                      ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:131: error: package R does not exist
        ImageView twittertim = (ImageView) findViewById(R.id.twitter_technologx);
                                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:146: error: package R does not exist
        getMenuInflater().inflate(R.menu.menu_main, menu);
                                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:158: error: package R does not exist
        if (id == R.id.action_settings) {
                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:163: error: package R does not exist
            case R.id.changelog:
                  ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:169: error: package R does not exist
                popup.setContentView(R.layout.dialog);
                                      ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:171: error: package R does not exist
                TextView text1 = (TextView) popup.findViewById(R.id.text1);
                                                                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:172: error: package R does not exist
                text1.setText(getString(R.string.changelog_title));
                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:174: error: package R does not exist
                TextView text2 = (TextView) popup.findViewById(R.id.text2);
                                                                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:175: error: package R does not exist
                text2.setText(getString(R.string.changelog));
                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/AboutActivity.java:179: error: package R does not exist
                Button closebutton = (Button) popup.findViewById(R.id.button2);
                                                                  ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:45: error: package R does not exist
        toolbar = (Toolbar) findViewById(R.id.toolbar);
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:51: error: package R does not exist
                    .playOn(findViewById(R.id.imageView4));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:55: error: package R does not exist
                    .playOn(findViewById(R.id.imageView3));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:61: error: package R does not exist
                    .playOn(findViewById(R.id.imageView3));
                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:66: error: package R does not exist
        ScrollView scrollView = (ScrollView) findViewById(R.id.scroll);
                                                           ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:67: error: package R does not exist
        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
                                                                        ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:97: error: package R does not exist
        startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(getString(R.string.playstore_link))));
                                                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:102: error: package R does not exist
        startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(getString(R.string.googleplus_link))));
                                                                          ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/BaseActivity.java:208: error: package R does not exist
            in = assetManager.open(getString(R.string.apkfilename));
                                              ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/CalligraphyApplication.java:19: error: package R does not exist
                        .setFontAttrId(R.attr.fontPath)
                                        ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:20: error: package R does not exist
        return R.layout.activity_main;
                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:28: error: package R does not exist
        getMenuInflater().inflate(R.menu.menu_main, menu);
                                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:40: error: package R does not exist
        if (id == R.id.action_settings) {
                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:44: error: package R does not exist
        if (id == R.id.action_about) {
                   ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:51: error: package R does not exist
            case R.id.changelog:
                  ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:57: error: package R does not exist
                popup.setContentView(R.layout.dialog);
                                      ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:59: error: package R does not exist
                TextView text1 = (TextView) popup.findViewById(R.id.text1);
                                                                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:60: error: package R does not exist
                text1.setText(getString(R.string.changelog_title));
                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:62: error: package R does not exist
                TextView text2 = (TextView) popup.findViewById(R.id.text2);
                                                                ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:63: error: package R does not exist
                text2.setText(getString(R.string.changelog));
                                         ^
/Users/Technologx/Desktop/Android Projects/WeatherIconsDashboard/app/src/main/java/com/supremez/dashboard/MainActivity.java:67: error: package R does not exist
                Button closebutton = (Button) popup.findViewById(R.id.button2);
                                                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
69 errors
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Information:71 errors
Information:0 warnings
Information:See complete output in console

**Comment by timbremer** [comment]
I don't think you have the latest sources, please update using `git fetch origin`.
If that doesn't help, try cleaning the project or adding `import com.supremez.dashboard.R;` to the top of the DetailActivity.

**Comment by Technologx** [comment]
Alright I'll try that thank you do you happen to have a guide for this anywhere to let me know what's editable and what's not?

**Comment by timbremer** [comment]
There is no guide and we stopped developing this dashboard 1 1/2 years ago. You should really take a look at alternatives like Polar: https://github.com/afollestad/polar-dashboard

**Comment by Technologx** [comment]
I looked at this one so I could do weather icons for others to use PolarDash Board nor does IconShowcase Dashboard give the option of just assests.

**Comment by arturomb21** [comment]
You don’t need a Dashboard for make weather icons. This Dashboard was created as a wallpaper support for a zooper pack.

**Comment by Technologx** [comment]
If you look at the dashboard's assets folder there's a folder for iconsets which is what weather icons are.

**Comment by arturomb21** [comment]
I know, im the creator of the Dashboard along with Tim.

**Comment by Technologx** [comment]
Then why not update this to help people like me looking for a dashboard to use just for weather icons and widgets?

**Comment by Technologx** [comment]
I'm not trying to come of rude but there are people out there who just want to do weather icons or make widgets. Is there anyway I can edit the code to add my info to the about section?

**Comment by timbremer** [comment]
Of course, that's the reason this thing is open-sourced.
Put your resources in `/assets`, edit the strings and you should be good to go.

**Comment by Technologx** [comment]
Would you be ok if I forked this project and edited it for others to use then link it on my website and community on G+?

**Comment by Technologx** [comment]
So could anyone help me with adding the settings to the code to switch between the light and dark layouts you have in the dashboard?

**Comment by arturomb21** [comment]
Sorry Kevin but I think that not, we stopped the development of this
dashboard 2 years ago.
