### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by arturomb21** [Supremez/Dashboard#5]
Trying to implement set and crop wallpaper. But we have a problem:

The Bitmap is a lot compressed and we lost all the quality of the image.

Anyone who knows how to implement this without compressing the bitmap?

Thanks.

**Comment by tbremer19** [comment]
Could you solve it with your last commit?

**Comment by arturomb21** [comment]
Not. I need more tests today.

**Comment by arturomb21** [comment]
Resolved the Issue.
